# First-Day Survey

First, fill out the [first-day survey](https://goo.gl/forms/MRg5GpHvd6ECMcav1), which is an anonymous survey with some fun questions. This notebook will read in [the responses](https://docs.google.com/spreadsheets/d/1NzcMTL7INHHee8CDdcSPPgyKuiEg0YTkqoOkJbI9JmQ/) into a `pandas` `DataFrame`.

We'll do this by issuing a request to the [Google Sheets REST API](https://developers.google.com/sheets/api/reference/rest/), which returns the data in JSON format. Don't worry if all of this is Greek to you now. You'll learn what all of this means, later in the course. For now, just run the cell below and trust that it fetches the data in the spreadsheet above.

In [15]:
import requests

API_KEY = "AIzaSyAu1_itQekOyIXrIKIfn9sJrLVVGCL3Unc"
SPREADSHEET_ID = "1NzcMTL7INHHee8CDdcSPPgyKuiEg0YTkqoOkJbI9JmQ"

url = "https://sheets.googleapis.com/v4/spreadsheets/%s/values/A1:I100?key=%s" % (
    SPREADSHEET_ID,
    API_KEY
)
req = requests.get(url)

All of the survey responses are in the `values` attribute of the resulting JSON object. Let's extract that and construct a `pandas` `DataFrame` out of it.

In [16]:
import pandas as pd
df = pd.DataFrame(req.json()["values"])
df

,0,1,2,3,4,5,6,7,8
0,Timestamp,What is your major?,How many older siblings do you have?,How many younger siblings do you have?,Which would you rather be?,What is your favorite color?,What day of the month were you born?,Do you think that we would need more or less t...,How many basketballs do you think we would need?
1,1/8/2019 8:42:05,STAT,0,2,the worst player on a great team,orange,10,more,1500
2,1/8/2019 8:42:10,STAT,1,0,the best player on a horrible team,Forest Green,29,less,700
3,1/8/2019 8:42:24,CSC,1,0,the best player on a horrible team,Blue,4,more,100000000
4,1/8/2019 8:42:27,CSC,1,0,the worst player on a great team,blue,25,more,3000
5,1/8/2019 8:42:29,political science,0,0,the worst player on a great team,red,18,more,2750
6,1/8/2019 8:42:33,CSC,1,1,the best player on a horrible team,Purple,11,more,2000
7,1/8/2019 8:42:40,SE,0,0,the best player on a horrible team,purple,23,more,2500
8,1/8/2019 8:42:51,CSC,0,1,the best player on a horrible team,Magenta,14,more,10000
9,1/8/2019 8:42:52,CSC,0,1,the best player on a horrible team,green,17,more,2000
10,1/8/2019 8:42:53,SE,0,2,the best player on a horrible team,Blue,21,less,15
11,1/8/2019 8:42:53,CSC,0,1,the worst player on a great team,Blue,26,more,10000
12,1/8/2019 8:42:55,CSC,0,2,the worst player on a great team,Blue,30,less,900
13,1/8/2019 8:42:57,CSC,1,1,the best player on a horrible team,blue,6,more,4000
14,1/8/2019 8:42:59,SE,0,2,the worst player on a great team,Orange,29,more,4000
15,1/8/2019 8:43:00,CSC,0,1,the worst player on a great team,Blue,6,more,6500
16,1/8/2019 8:43:00,STAT,0,1,the worst player on a great team,Green,22,more,2000
17,1/8/2019 8:43:04,CSC,0,0,the worst player on a great team,Blue,1,more,100000000000
18,1/8/2019 8:43:12,STAT,2,0,the worst player on a great team,green,5,less,800
19,1/8/2019 8:43:16,STAT,0,0,the worst player on a great team,Blue,6,more,1500
20,1/8/2019 8:43:19,SE,0,3,the best player on a horrible team,Light Blue,7,less,700
21,1/8/2019 8:43:22,STAT,0,2,the worst player on a great team,Blue,19,more,1500
22,1/8/2019 8:43:27,CSC,0,0,the worst player on a great team,green,29,more,5000
23,1/8/2019 8:43:30,CSC,0,2,the best player on a horrible team,Burgundy,11,more,5000
24,1/8/2019 8:43:37,CSC,1,0,the best player on a horrible team,Blue,26,more,1500
25,1/8/2019 8:43:38,STAT,0,1,the worst player on a great team,Blue,9,more,8000
26,1/8/2019 8:43:51,MATH,2,0,the worst player on a great team,Orange,8,more,15000
27,1/8/2019 8:43:52,SE,1,0,the worst player on a great team,blue,14,more,23076
28,1/8/2019 8:43:57,CSC,1,1,the best player on a horrible team,blue,11,more,1900
29,1/8/2019 8:44:09,SE,1,2,the worst player on a great team,aegean blue,29,more,1300
30,1/8/2019 8:44:18,CSC,0,0,the worst player on a great team,red,11,more,4000
31,1/8/2019 8:44:21,CSC,2,0,the worst player on a great team,White,27,more,5000
32,1/8/2019 8:44:44,MATH,0,1,the worst player on a great team,Red,6,more,3000
33,1/8/2019 8:44:51,SE,0,2,the worst player on a great team,Blue,4,more,3000
34,1/8/2019 8:44:52,CSC,0,1,the best player on a horrible team,Green,17,more,2500
35,1/8/2019 8:44:57,STAT,0,1,the worst player on a great team,blue,12,more,9000
36,1/8/2019 10:35:16,SE,0,1,the best player on a horrible team,Caribbean green,21,more,5000
37,1/8/2019 13:12:07,CSC,0,1,the worst player on a great team,Green,4,less,50000
38,1/8/2019 13:24:00,STAT,0,1,the worst player on a great team,Blue,24,less,75000
39,1/8/2019 13:26:14,SE,1,0,the best player on a horrible team,Green,17,less,6000
40,1/8/2019 13:27:15,CSC,0,1,the best player on a horrible team,Blue,16,less,30000
41,1/8/2019 13:29:49,CSC,0,0,the worst player on a great team,Blue,9,less,16000
42,1/8/2019 13:31:01,CSC,0,1,the worst player on a great team,green,16,less,50000
43,1/8/2019 13:32:20,CSC,0,1,the worst player on a great team,blue,23,less,60000
44,1/8/2019 13:32:32,CSC,0,1,the best player on a horrible team,Blue,27,more,200000
45,1/8/2019 13:33:30,CSC,2,0,the worst player on a great team,Red,20,less,75000
46,1/8/2019 13:34:02,STAT,0,1,the worst player on a great team,Green,1,less,7000
47,1/8/2019 13:34:15,CSC,0,1,the worst player on a great team,all of them,23,less,10000
48,1/8/2019 13:35:14,STAT,1,0,the worst player on a great team,Yellow,28,less,27000
49,1/8/2019 13:38:33,CSC,2,0,the best player on a horrible team,Navy,22,less,30000
50,1/8/2019 13:38:53,SE,1,0,the best player on a horrible team,Mint Green,24,more,300000
51,1/8/2019 13:40:52,CSC,1,1,the worst player on a great team,Blue,19,more,580000
52,1/8/2019 13:40:22,CSC,0,1,the best player on a horrible team,Black,21,less,10000
53,1/8/2019 13:40:30,CSC,2,1,the worst player on a great team,Navy Blue,4,less,8000
54,1/8/2019 13:43:17,CSC,2,0,the worst player on a great team,Phthalo Blue,9,less,80000
55,1/8/2019 13:47:49,BUS,1,0,the worst player on a great team,Black,25,more,100001

There's a problem. The first row (i.e., row 0) is clearly supposed to be the column names. To make things right, we can rename the columns to the values in row 0 and drop row 0 from the `DataFrame`.

In [17]:
df.rename(columns=df.iloc[0]).drop(0)

,Timestamp,What is your major?,How many older siblings do you have?,How many younger siblings do you have?,Which would you rather be?,What is your favorite color?,What day of the month were you born?,Do you think that we would need more or less than 100000 basketballs?,How many basketballs do you think we would need?
1,1/8/2019 8:42:05,STAT,0,2,the worst player on a great team,orange,10,more,1500
2,1/8/2019 8:42:10,STAT,1,0,the best player on a horrible team,Forest Green,29,less,700
3,1/8/2019 8:42:24,CSC,1,0,the best player on a horrible team,Blue,4,more,100000000
4,1/8/2019 8:42:27,CSC,1,0,the worst player on a great team,blue,25,more,3000
5,1/8/2019 8:42:29,political science,0,0,the worst player on a great team,red,18,more,2750
6,1/8/2019 8:42:33,CSC,1,1,the best player on a horrible team,Purple,11,more,2000
7,1/8/2019 8:42:40,SE,0,0,the best player on a horrible team,purple,23,more,2500
8,1/8/2019 8:42:51,CSC,0,1,the best player on a horrible team,Magenta,14,more,10000
9,1/8/2019 8:42:52,CSC,0,1,the best player on a horrible team,green,17,more,2000
10,1/8/2019 8:42:53,SE,0,2,the best player on a horrible team,Blue,21,less,15
11,1/8/2019 8:42:53,CSC,0,1,the worst player on a great team,Blue,26,more,10000
12,1/8/2019 8:42:55,CSC,0,2,the worst player on a great team,Blue,30,less,900
13,1/8/2019 8:42:57,CSC,1,1,the best player on a horrible team,blue,6,more,4000
14,1/8/2019 8:42:59,SE,0,2,the worst player on a great team,Orange,29,more,4000
15,1/8/2019 8:43:00,CSC,0,1,the worst player on a great team,Blue,6,more,6500
16,1/8/2019 8:43:00,STAT,0,1,the worst player on a great team,Green,22,more,2000
17,1/8/2019 8:43:04,CSC,0,0,the worst player on a great team,Blue,1,more,100000000000
18,1/8/2019 8:43:12,STAT,2,0,the worst player on a great team,green,5,less,800
19,1/8/2019 8:43:16,STAT,0,0,the worst player on a great team,Blue,6,more,1500
20,1/8/2019 8:43:19,SE,0,3,the best player on a horrible team,Light Blue,7,less,700
21,1/8/2019 8:43:22,STAT,0,2,the worst player on a great team,Blue,19,more,1500
22,1/8/2019 8:43:27,CSC,0,0,the worst player on a great team,green,29,more,5000
23,1/8/2019 8:43:30,CSC,0,2,the best player on a horrible team,Burgundy,11,more,5000
24,1/8/2019 8:43:37,CSC,1,0,the best player on a horrible team,Blue,26,more,1500
25,1/8/2019 8:43:38,STAT,0,1,the worst player on a great team,Blue,9,more,8000
26,1/8/2019 8:43:51,MATH,2,0,the worst player on a great team,Orange,8,more,15000
27,1/8/2019 8:43:52,SE,1,0,the worst player on a great team,blue,14,more,23076
28,1/8/2019 8:43:57,CSC,1,1,the best player on a horrible team,blue,11,more,1900
29,1/8/2019 8:44:09,SE,1,2,the worst player on a great team,aegean blue,29,more,1300
30,1/8/2019 8:44:18,CSC,0,0,the worst player on a great team,red,11,more,4000
31,1/8/2019 8:44:21,CSC,2,0,the worst player on a great team,White,27,more,5000
32,1/8/2019 8:44:44,MATH,0,1,the worst player on a great team,Red,6,more,3000
33,1/8/2019 8:44:51,SE,0,2,the worst player on a great team,Blue,4,more,3000
34,1/8/2019 8:44:52,CSC,0,1,the best player on a horrible team,Green,17,more,2500
35,1/8/2019 8:44:57,STAT,0,1,the worst player on a great team,blue,12,more,9000
36,1/8/2019 10:35:16,SE,0,1,the best player on a horrible team,Caribbean green,21,more,5000
37,1/8/2019 13:12:07,CSC,0,1,the worst player on a great team,Green,4,less,50000
38,1/8/2019 13:24:00,STAT,0,1,the worst player on a great team,Blue,24,less,75000
39,1/8/2019 13:26:14,SE,1,0,the best player on a horrible team,Green,17,less,6000
40,1/8/2019 13:27:15,CSC,0,1,the best player on a horrible team,Blue,16,less,30000
41,1/8/2019 13:29:49,CSC,0,0,the worst player on a great team,Blue,9,less,16000
42,1/8/2019 13:31:01,CSC,0,1,the worst player on a great team,green,16,less,50000
43,1/8/2019 13:32:20,CSC,0,1,the worst player on a great team,blue,23,less,60000
44,1/8/2019 13:32:32,CSC,0,1,the best player on a horrible team,Blue,27,more,200000
45,1/8/2019 13:33:30,CSC,2,0,the worst player on a great team,Red,20,less,75000
46,1/8/2019 13:34:02,STAT,0,1,the worst player on a great team,Green,1,less,7000
47,1/8/2019 13:34:15,CSC,0,1,the worst player on a great team,all of them,23,less,10000
48,1/8/2019 13:35:14,STAT,1,0,the worst player on a great team,Yellow,28,less,27000
49,1/8/2019 13:38:33,CSC,2,0,the best player on a horrible team,Navy,22,less,30000
50,1/8/2019 13:38:53,SE,1,0,the best player on a horrible team,Mint Green,24,more,300000
51,1/8/2019 13:40:52,CSC,1,1,the worst player on a great team,Blue,19,more,580000
52,1/8/2019 13:40:22,CSC,0,1,the best player on a horrible team,Black,21,less,10000
53,1/8/2019 13:40:30,CSC,2,1,the worst player on a great team,Navy Blue,4,less,8000
54,1/8/2019 13:43:17,CSC,2,0,the worst player on a great team,Phthalo Blue,9,less,80000
55,1/8/2019 13:47:49,BUS,1,0,the worst player on a great team,Black,25,more,100001

Now save the `DataFrame` above into a variable, and start exploring this data set!

In [18]:
df = df.rename(columns=df.iloc[0]).drop(0)